name: Build and Deploy docs

on:
  pull_request:
  push:
  release:
    types:
      - published

defaults:
  run:
    shell: bash

# no permissions by default
permissions: {}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Setup Micromamba ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@b09ef9b599704322748535812ca03efb2625677b  # v2.0.5
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 pip --channel conda-forge

    - name: Install library
      shell: bash -l {0}
      run: |
        python -m pip install .[test,plotting,docs]
        conda install pandoc

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        jupyter nbconvert --to notebook --execute notebooks/00-quick_intro.ipynb --output=00-quick_intro-output.ipynb
        jupyter nbconvert --to notebook --execute notebooks/01-plotting_intro.ipynb --output=01-plotting_intro-output.ipynb
        mv notebooks/*output.ipynb docs/source/
        pushd docs
        make clean html linkcheck
        popd

    - name: Deploy
      if: success() && github.event_name == 'release'
      uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e  # v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
