name: Tests

# no permissions by default
permissions: {}

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  run:
    name: "Tests (${{ matrix.os }} ${{ matrix.python-version }} mpl=${{ matrix.mpl }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.11", "3.15.0-rc.2" ]
        os: [ ubuntu-latest ]
        mpl: [ false ]
        include:
          - python-version: "3.11"
            os: ubuntu-latest
            mpl: true
          - os: windows-latest
            python-version: "3.15.0-rc.2"
            mpl: false
          - os: macos-latest
            python-version: "3.15.0-rc.2"
            mpl: false
          - os: macos-15-intel
            python-version: "3.15.0-rc.2"
            mpl: false
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}

    # Run full tests only on oldest Python to avoid re-writing the the mpl images every new mpl release.
    - name: Test images
      if: matrix.mpl == true
      run: |
        python -m pip install .[test,plotting]
        python -m pytest -rxs --mpl tests

    - name: Tests
      if: matrix.mpl == false
      run: |
        python -m pip install .[test]
        python -m pytest -rxs --mpl tests/test_fetchers.py
